# Generated by Django 4.2.15 on 2026-09-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price_per_page', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('pages', models.PositiveIntegerField()),
                ('copies', models.PositiveIntegerField()),
                ('color', models.BooleanField(default=False)),
                ('cost', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('delivery_address', models.JSONField()),
            ],
        ),
    ]
